config/contracts.js
test/escrow_spec.js

Avoid to use `0x0` for fake address.
This is what is causing the test to fail

fix: use real zero address

---

config/blockchain.js
test/escrow_spec.js
test/license_spec.js
utils/testUtils.js

Using  `embark test --node=embark` wa sbroken, because:
1. The tests needed at least two accounts, so I added another one in the blockchain config
2. The revert error message is not the same for the VM and the real node
3. The provider function is not the same for the vm and the real node
also a bit of auto indents and linting

Fix tests using a node

---

config/contracts.js

Basically, we have address for deployement that used to be coming from the mnemonic and we gave it SNT, but in the Dapp, we use the node's account and it has 0. Now, the first account is the node's.
Tell me if this breaks something (is there a reason why we would need to use the custom address as deployment)

fix(accounts): add node accounts as first accounts so that they work in the dapp

---

app/js/components/Buyer/SorterFilter.jsx
app/js/components/Buyer/SorterFilter.scss

Fixes some weird behaviours the filtyer menu had when closing.
It's still not perfect on browser, because on opening the menu will bounce a little bit, but on mobile it doesn't happen. (it's because we use percentage width and padding, but then we hit the max width so it bounces back to the max.

fix(filter-menu): fix filter menu close glitches

---

app/css/bootstrap-overrides.scss
app/js/components/UserInformation/index.jsx
app/js/features/arbitration/saga.js
app/js/features/escrow/selectors.js
app/js/features/metadata/saga.js
app/js/locales/en.json
app/js/pages/Home/index.jsx
app/js/pages/MyProfile/components/Disputes.jsx
app/js/pages/MyProfile/index.jsx
app/js/pages/MyProfile/index.scss
config/data.js

Display escrows in dispute in the profile for Arbiters, and also hide/show buy and sell button for this role.
Design has a Date for open disputes, however, this information is not stored in the contract. (It's currently marked as "TODO"). **A decision must be made on this regard.**
To see the arbitration profile,  you must call `setArbitrator(_addr)` in the contract explorer of Embark Cockpit

feat: display escrows in dispute for arbiters

---

src/js/features/escrow/saga.js

This caused an issue on the profile where the seller name was always displayed instead of the buyer one (when on the seller's profile)

fix(escrow): get correct buyer info by fixing address used

---

src/js/wizards/Buy/1_Trade/index.jsx

For now, set limits from 0 to 999999 so that we can test however we want.
We'll just need to pass the real values once we have them in the contract

Remove min max limits on Buy

---

src/js/layout/App.jsx

This was caused by the `<Redirect>` tag applying before the Wizard route being rendered or something.
So now uses the fallback mechanism of the `<Switch>` to go to 404 instead. Only downside is that it won't show `/404` but the page will be the right one anyway.

Fix getting 404 on reloading a wizard page

---

contracts/teller-network/Escrow.sol
embarkConfig/contracts.js
package.json
shared.chains.json
src/js/components/Loading/index.jsx
src/js/features/escrow/actions.js
src/js/features/escrow/reducer.js
src/js/features/escrow/saga.js
src/js/features/escrow/selectors.js
src/js/features/network/selectors.js
src/js/pages/Escrow/components/CardEscrowBuyer.jsx
src/js/pages/Escrow/components/CardEscrowSeller.jsx
src/js/pages/Escrow/components/Mining.jsx
src/js/pages/Escrow/index.jsx
src/js/pages/MyProfile/components/Trades.jsx
src/js/store.js
src/js/ui/TxHash/index.js
src/js/utils/saga.js
src/js/wizards/Buy/1_Trade/index.jsx
stories/components/loading.stories.jsx
stories/components/mining.stories.jsx
stories/components/userInformation.stories.jsx
yarn.lock

This is a pretty big one in the fact that it touches the whole state management of the escrows.
The goal: make the flow more reactive and more informative.
With this, when a Tx is sent, the user gets a link to etherscan with the tx hash. He can also go back to the profile and see the actual state of the TX and go back to it and when it's done, all the states are correctly updated.
Includes a couple of other fixes and improvement, but here is what the new states in the list look like:

Improve state management of escrows

---

src/js/features/arbitration/saga.js
src/js/pages/Arbitration/components/EscrowDetail.jsx
src/js/pages/Arbitration/index.jsx
src/js/pages/Arbitration/index.scss
src/js/pages/MyProfile/components/Dispute.jsx
src/js/pages/MyProfile/components/Disputes.jsx
src/js/pages/MyProfile/index.jsx

We fetched the buyer and seller info from the chain for arbitrations when it was useless. That's the responsibility of the metadata state, so I moved that logic in the Dispute component and we only load the profiles if they weren't already loaded.

Remove useless blockchain calls and use the state instead

---

src/js/layout/App.jsx
src/js/ui/BackButton/index.jsx

Adds a back button (that takes you back), on all pages except the ones that have been blcklisted.
Current blacklist:
- home
- Offer list
- sell wizard
You can add pages in the component by just adding to the array and you can use a `*` to match all that starts with something, like I did with the sell path (`/sell/*`)
Need to check if the blacklist work on the gh-pages, because I'm not sure how the pathname works there.

Add a Back button on all pages except some

---

shared.chains.json
src/js/pages/Escrow/index.jsx

Before, we didn,t actually show any error on escrow tx errors. This was further accentuated by the fact that we reset the escrow states when loading the escrow page.
With this change, the error is displayed and also it is persisted when changing page.
Downside: if you start a TX for escrow 1, go to your profile while it's mining, it errors and then you go to escrow 2 (not the same escrow), you will see the error of escrow 1.
At least it shows the error, and the user should be smart enough to understand that it's related to the tx he did in the first escrow.
We should however refactor how we handle escrow states so that it is per escrow, instead of global escrow states.

Show error on escrow even when switching page

---

src/js/features/escrow/actions.js
src/js/features/escrow/reducer.js
src/js/features/escrow/selectors.js
src/js/pages/Escrow/components/CardEscrowBuyer.jsx
src/js/pages/Escrow/components/CardEscrowSeller.jsx
src/js/pages/Escrow/index.jsx

Big clean up so that the escrow states are inside the escrows instead of being "global", that way, it is way easier to manage changing the escrow, so we will no longer have the issue of an escrow being completed and the others are still completed and also errors are also gonna perpetuate correctly in the right escrow.

Put status in escrow object to better handle states

---

README.md
contracts/teller-network/Escrow.sol
embarkConfig/contracts.js
package.json
src/js/features/escrow/actions.js
src/js/features/escrow/saga.js
src/js/utils/networks.js
yarn.lock

1. Adds procedure to run a tabookey relayer locally
2. Adds gasless functionality for contract to only apply when the user has < 500000*gasPrice in balance, and only ETH offers with some throttling restrictions
3. Ropsten network section (no contract config yet)

feat: add gasless functionality to escrow contract

---

src/js/features/prices/selectors.js
src/js/pages/Escrow/components/EscrowDetail.jsx
src/js/pages/Escrow/index.jsx

Percent can be easily changed
I'm not sure if I need to put the margin in my calculations? Like, what if the seller put amunally -10% 
margin, do we still put the warning?
Bogus data btw, ETH is not really 100 :P

feat: show a message when the trade asset price is 10% lower

---

contracts/common/MessageSigned.sol
contracts/teller-network/Escrow.sol
contracts/teller-network/MetadataStore.sol
embarkConfig/contracts.js
src/js/features/escrow/actions.js
src/js/features/escrow/saga.js
src/js/features/metadata/actions.js
src/js/features/metadata/constants.js
src/js/features/metadata/reducer.js
src/js/features/metadata/saga.js
src/js/features/metadata/selectors.js
src/js/wizards/Buy/0_Contact/index.jsx
src/js/wizards/Buy/1_Trade/index.jsx
test/escrow_spec.js
test/funding_escrows_spec.js
test/metadata_store_spec.js

Stops metadata from depending on the Escrow contract.
This includes a flow change:
1. Signature is being asked in the buyer flow after the username and contact code screen.
2. Removes the redirect on the username/contact code screen, due to this signature requiring a nonce.

feat: decouple metadata from escrow, and ask for signatures in escrow creation

---

src/js/features/escrow/actions.js
src/js/pages/Escrow/components/EscrowDetail.jsx
src/js/wizards/Buy/1_Trade/index.jsx

I didn't get to test it a lot, because when I created a new escrow, the warning wasn't there, but this should fix it anyway

fix(escrow-detail): use only two decimals to calculate the diff

---

src/js/features/network/reducer.js

This was causing an issue where in the open trade screen, if you refreshed, it would load infinitively, because the seller balance was getting overwritten

fix(network-reducer): fix updating the balance and not override

---

contracts/teller-network/Fees.sol
shared.chains.json
test/escrow_spec.js

An escrow with no arbitrator has its address set as 0x0, but  SNT cannot be sent to 0x0, for reasons
So instead, we send everything to the fee destination (later the staking pool)

Fix releasing SNT escrows where there is no arbitrator

---

src/js/features/license/reducer.js
src/js/wizards/Sell/0_Location/index.jsx
src/js/wizards/Sell/6_Margin/components/__snapshots__/MarginSelectorForm.test.jsx.snap
src/js/wizards/Wizard.jsx

This probably fixes the infinite loop. 
The wizard was bugged because `hash` was empty, so the step reseted to 0 each time, now it doesn't.
We had a quick 404 on refresh in the wizard, because checking the license put `licenseOwner` to false, but it was useless.
Finally, removed the redirect on location being already present. This enables changing the location and also, redirects are dangerous.

Fix wizard reseting on refresh and remove redirect on location

---

src/js/features/escrow/helpers.js
src/js/locales/en.json
src/js/pages/ArbitrationLicense/index.jsx
src/js/pages/MyProfile/components/Trades.jsx
src/js/pages/MyProfile/components/Trades.scss
src/js/pages/MyProfile/components/__snapshots__/Trades.test.jsx.snap
src/js/wizards/Sell/6_Margin/components/__snapshots__/MarginSelectorForm.test.jsx.snap

Since the trades list in the profile can grow infinetly, here are some improvements:
- Limit height and put a scroll 
- Add filters to
- Select a specific state
- Hide completed trades (released, canceled, expired, etc)

Improve trades list

---

src/js/ui/BackButton/index.jsx

This fixes the issues where you click on the back button and it seems like nothing happens. 
What actually is happening is that you back to a page that redirects you to the page where you were.
Example: clicking on one of your offers in the offer list usually brings to the seller's profile, but since it's yourself, it redirects to your profile. Then, clicking `Back` doesn't bring to the list, you were stuck.
Now, this detects the redirects and goes back to the previous page

fix: fix back button when a redirect happens

---

src/js/components/Offer/index.jsx
src/js/features/prices/reducer.js
src/js/features/prices/saga.js
src/js/features/prices/selectors.js
src/js/layout/App.jsx
src/js/locales/en.json
src/js/pages/Home/index.jsx
src/js/pages/Profile/components/Offer.jsx
src/js/utils/transaction.js
src/js/wizards/Sell/6_Margin/components/MarginSelectorForm.jsx

This makes us resistant against failures in fetching the prices. 
Previously, if Crypto Compare was down, the Dapp would crash in certain pages (offer list for example).
Now, we can still navigate the pages, but the prices are not shown and it's no longer possible to open a trade, until the prices come back available.

Make Teller still work if Crypto compare is down

---

src/js/layout/App.jsx
src/js/layout/Header/index.jsx
src/js/pages/Arbitrators/index.jsx
src/js/pages/MyProfile/index.jsx

Previously there was no way for the users to become an arbitrator since the button is located in the profile, and the only way to access it was if the user already had a profile, product of being a seller or having performed a trade.
With this PR, I hide the user information panel, but still show the buttons that once clicked would request that the user acquires a license

feat: allow users to go to profile page even if they don't have a profile

---

contracts/teller-network/Escrow.sol
contracts/teller-network/EscrowRelay.sol
contracts/teller-network/IEscrow.sol
src/js/components/Reputation/__snapshots__/index.test.jsx.snap
src/js/features/escrow/actions.js
src/js/features/escrow/saga.js
src/js/pages/Arbitration/components/EscrowDetail.jsx
src/js/pages/Escrow/components/EscrowDetail.jsx
src/js/pages/Escrow/index.jsx
src/js/wizards/Buy/2_ConfirmTrade/index.jsx
src/js/wizards/Sell/2_Currency/components/__snapshots__/FiatSelectorForm.test.jsx.snap
src/js/wizards/Sell/3_Location/components/__snapshots__/SellerPosition.test.jsx.snap

Since we used  2 decimal places, in the case of currencies that have a low price, we were losing precision in the calculation of prices between the buy wizard, confirmation screen and escrow page.
This changes the contract so we store the fiat amount the user is willing to pay for an amount of tokens, and then determining the asset price is done by dividing this fiat amount by the token amount. 
Additionally, I increased the number of decimals to 4 in some pages,

fix: fiat price among different screens

---

src/js/layout/App.jsx
src/js/wizards/Sell/3_Location/index.jsx
src/js/wizards/Sell/4_Contact/index.jsx
src/js/wizards/Sell/7_Limits/index.jsx
src/js/wizards/Sell/8_Summary/components/SellSummary.js
src/js/wizards/Sell/8_Summary/index.jsx

- Add a summary page at the end of the create offer wizard
- Note that it tells the user if the username, location or status code changes, to show that it changes for him/her and not the offer
- Fix the location and contact seller pages to have the profile values by default (that way, no need to write your username again)

Add sell summary + 2 small seller fixes

---

src/js/features/approval/saga.js
src/js/features/emailNotifications/saga.js
src/js/features/metadata/saga.js
src/js/pages/Escrow/index.jsx

This is required since the email notifier has links to the escrow page instead of going to the profile.

fix: EIP1102 functionality for escrow page used when browsing the URL directly

---

package.json
src/index.js
src/js/layout/Header/index.jsx
yarn.lock

Change the back button in the profile page to go back to `/buy` if the last page is another `profile` page (eg settings)
Also fix a bug where going back, the X button didn't disappear. It was caused by the order of the HOCs.

fix: go back to buy page when last page is the profile still

---

src/css/bootstrap-overrides.scss
src/js/layout/Header/index.scss
src/js/pages/Home/index.scss
src/js/wizards/hoc/withFooter.jsx
src/js/wizards/hoc/withFooter.scss

Before, we had Previous and Next, Now Next is full size and alone (easier to see)
Also, on desktop, the footer was a the very bottom, so it was annoying and hard to see, now the Footer follows the content, but sticks to the bottom of the page (`position: sticky` is very cool)
Mobile: 
Desktop:
Desktop with long list (the utility of sticky):

Change footer to be full size Next button and Up when on desktop

---

src/js/features/metadata/saga.js

This is something we might have to refactor more globally later. We currently handle the upper limit as both `limitH` and `limitU` (even in the contract

fix: limitH being limitU in the creation of the escrow

---

src/js/wizards/Sell/0_Asset/index.jsx

Change doesn't seem to be needed, but got triggered by this: https://www.pivotaltracker.com/story/show/170643021
I'm not sure how he managed to do it, he's a bug magician!

fix: hide footer if eip1102 gets disabled

---

src/js/features/metadata/reducer.js

The problem was there was no rating for the first time sellers, so `average` was `NaN`, so multiplication didn't work => 0.

fix: rating reducer if the user was never rated before

---

.travis.yml

Because they are useless
Once my PR in Embark is merged and we get a new nightly (tomorrow probably), we'll be able to actually rely on CI

chore: deactivate unit tests on CI

---

src/js/features/metadata/selectors.js
src/js/pages/Home/index.jsx
src/js/pages/OffersList/index.jsx

This caused an issue in the Filter counters, because they counted offers that were not visible

fix: remove zero address arbitrators from offer list in selector

---

shared.rinkeby.json
src/js/features/metadata/saga.js
src/js/layout/App.jsx

So, long story short, if a saga throws and is not caught, all other sagas stop working.
So the enable.ethereum still worked. Status still worked.
The reason why it worked in other browsers and not Status is because Status follows the EIP1102 spec and returns an error/throws on getAccounts if the permission is not there yet.
We fixed it in Embark, but we still had one place in Teller where we called `getAccounts` without catching and it's the `verifyAccount`.
Since it was not caught, all the other sagas in the file stopped working, that includes the `enableEthereum` one, hence why it didn't work.
You might say: `But Jonathan, the `verifyAccount` has been there for a while, why does it crash now, with the new RCs?`
I was not sure, until I remembered one thing: In the new RC, you need to …

fix: catch errors in getAccounts so that the saga doesn't explode

---

src/js/features/metadata/selectors.js
src/js/layout/Header/index.jsx
src/js/wizards/Buy/0_Trade/index.jsx

- Fix case where if you're on the Profile as your first screen, the X doesn't really work.
- Now goes to /buy
- Fix blank screen on offer when changing account because offer is not defined yet
- Fix always asking for wallet enabling, when the account is already enabled, we will have it's defaultAccount

Fix issues about changing account

---

contracts/teller-network/Arbitrable.sol
contracts/teller-network/Escrow.sol

This change allows anyone to call the `escalateDispute` function on an escrow to automatically assign the dispute to the fallback arbitrator. We can then add in the escrow page an action for the users to call this function once the timeout date is reached.

feat: allow specifying a timeout for arbitrators and escalating a dispute to the fallback arbitrator once the timeout passes.

---

package.json
yarn.lock

I forked the original library and added the icon. I didn't add the PNG version, but we don't need it so whatever.

feat: update to new crypto icon library which has the DAI icon

---

SWARM.md
src/js/pages/Arbitration/components/ContactUser.jsx
src/js/pages/Escrow/components/EscrowDetail.jsx

We've replaced https://get.status.im/ with https://join.status.im/ for deep links.

fix use of legacy get.status.im domain
