- config/contracts.js
- contracts/escrow.sol
- contracts/pausable.sol
- test/escrow_spec.js
- utils/testUtils.js
> feat: add escrow contract

- app/js/components/EscrowList.jsx
- app/js/features/escrow/helpers.js
- package.json
- stories/createEscrowForm.stories.jsx
- stories/escrowList.stories.jsx
- stories/sellerList.stories.jsx
- yarn.lock
Storybook entries for:
- create escrow form
- escrow list
- seller list
> Add stories for escrows

- app/js/features/escrow/reducer.js
- contracts/teller-network/Escrow.sol
I needed to add the amount to the Created event, but I think it's fine
> feat(escrow-list): add new escrow in list when added

- .babelrc
- app/js/components/License.test.jsx
- app/js/components/__snapshots__/License.test.jsx.snap
- app/js/features/license/actions.test.js
- app/js/features/license/reducer.test.js
- app/js/setupTests.js
- package.json
- yarn.lock
Add test for:
* reducer
* actions
* component
As a first example I used the License
> feat: add first unit test structure

- .storybook/webpack.config.js
- app/css/Form.scss
- app/js/components/ArbitrationList.jsx
- app/js/components/CreateEscrowForm.jsx
- app/js/components/EscrowList.jsx
- app/js/components/IncludeSignatureForm.jsx
- app/js/components/License.jsx
- app/js/features/escrow/helpers.js
- app/js/features/escrow/reducer.js
- app/js/features/escrow/selectors.js
- app/js/locales/en.json
- app/js/validators.js
- package.json
- stories/escrowList.stories.jsx
- yarn.lock
> Add create escrow form validation

- app/js/components/__snapshots__/License.test.jsx.snap
Think about running: `test:unit` and `test:unit --updateSnapshot` if you like the changes!
> fix: unit test

- app/js/components/Seller/FitSelectorForm.test.jsx
- app/js/components/Seller/MarginSelectorForm.test.jsx
- app/js/components/Seller/SellerAssets.test.jsx
- app/js/components/Seller/SellerContact.test.jsx
- app/js/components/Seller/SellerPaymentMethod.test.jsx
- app/js/components/Seller/SellerPosition.test.jsx
- app/js/components/Seller/__snapshots__/FitSelectorForm.test.jsx.snap
- app/js/components/Seller/__snapshots__/MarginSelectorForm.test.jsx.snap
- app/js/components/Seller/__snapshots__/SellerAssets.test.jsx.snap
- app/js/components/Seller/__snapshots__/SellerContact.test.jsx.snap
- app/js/components/Seller/__snapshots__/SellerPaymentMethod.test.jsx.snap
- app/js/components/Seller/__snapshots__/SellerPosition.test.jsx.snap
Add default test for seller UI
> chores: add seller test

- app/js/components/Buyer/SorterFilter.jsx
- app/js/components/Buyer/SorterFilter.scss
- app/js/containers/HomeContainer.scss
This is just UI components. It does nothing
> Add filter menu UI

- app/js/components/Buyer/OfferTrade.jsx
- app/js/components/Seller/FiatSelectorForm.jsx
- app/js/components/Seller/MarginSelectorForm.jsx
- app/js/components/Seller/SellerAssets.jsx
- app/js/components/Seller/SellerPaymentMethod.jsx
- app/js/components/Seller/SellerPosition.jsx
- app/js/components/Seller/__snapshots__/FiatSelectorForm.test.jsx.snap
- app/js/components/Seller/__snapshots__/SellerPaymentMethod.test.jsx.snap
- app/js/components/Seller/__snapshots__/SellerPosition.test.jsx.snap
> fix(style): change tip color to muted (dark)

- app/js/components/ui/CheckButton.jsx
- package.json
- yarn.lock
> feat(style): change checks to circles

- app/css/variable-overrides.scss
- app/js/components/License/LicenseBuy.jsx
- app/js/components/License/LicenseInfo.jsx
- app/js/components/License/LicenseInfo.scss
- app/js/components/License/__snapshots__/LicenseBuy.test.jsx.snap
- app/js/components/License/__snapshots__/LicenseInfo.test.jsx.snap
- app/js/components/YourSNTBalance.jsx
- app/js/components/__snapshots__/ContactForm.test.jsx.snap
- app/js/components/__snapshots__/StatusContactCode.test.jsx.snap
- app/js/components/__snapshots__/YourSNTBalance.test.jsx.snap
- app/js/containers/LicenseContainer.jsx
- app/js/locales/en.json
> feat(style): style license page

- app/js/containers/EditProfileContainer.jsx
- app/js/features/buyer/actions.js
- app/js/features/buyer/constants.js
- app/js/features/metadata/actions.js
- app/js/features/metadata/saga.js
- app/js/services/embarkjs.js
I had to add redux-thunk, because getting the ENS address in the action is way easier. Let me know if I shouldn't or there is a better way, but I couldn't find a good way to to it in the saga (especially since we use `doTransaction`).
> Enable specifying ENS names as contact codes

- app/js/components/UserInformation/Address.jsx
- app/js/features/metadata/selectors.js
> feat: display full address or compact on click / press and change Bitfinex to Cryptocompare

- app/js/components/ErrorInformation/404.jsx
- app/js/components/ErrorInformation/index.scss
- app/js/layout/App.jsx
- app/js/locales/en.json
- app/js/pages/MyProfile/components/__snapshots__/StatusContactCode.test.jsx.snap
> feat(page): add 404 page

- app/js/pages/License/components/Balance.jsx
- app/js/pages/License/components/__snapshots__/Balance.test.jsx.snap
- app/js/pages/MyProfile/components/__snapshots__/StatusContactCode.test.jsx.snap
- app/js/utils/numbers.js
- app/js/wizards/Sell/0_Asset/components/SellerAssets.jsx
Fix balance being red and too long assets
> Fix license and assets page

- app/js/features/metadata/constants.js
- app/js/pages/OffersList/components/SorterFilter.jsx
- app/js/pages/OffersList/components/SorterFilter.scss
- app/js/pages/OffersList/index.jsx
Makes the sort "work". It does work for the date. I couldn't add the sort by rating, because we'll need to implement the rating calculation per users first.
I also made it so we close the menu when choosing an option.
> feat(sorter): add sort by date and auto close menu when clicking

- app/css/bootstrap-overrides.scss
- app/js/components/Map/CustomInfoWindow.jsx
- app/js/components/Map/index.jsx
- app/js/components/Map/index.scss
- app/js/components/SearchBar/index.jsx
- app/js/features/metadata/selectors.js
- app/js/pages/OffersMap/index.jsx
- app/js/pages/Profile/index.jsx
Show the real user position in the Profile
Also, use real offer positions in the Map view!
> Use real position

- app/js/components/EditContact/__snapshots__/index.test.jsx.snap
- app/js/components/EditContact/index.jsx
- app/js/locales/en.json
- app/js/services/embarkjs.js
- app/js/utils/address.js
- app/js/validators.js
- app/js/wizards/Buy/0_Contact/index.jsx
- app/js/wizards/Sell/1_Contact/index.jsx
if a hexadecimal value is used, it must be a contact code of 65bytes
> fix: contact code validation

- app/js/features/escrow/actions.js
- app/js/wizards/hoc/withFooter.jsx
> Fix button not on same line in small screens

- src/css/bootstrap-overrides.scss
- src/js/layout/App.jsx
- src/js/layout/Header/index.jsx
Adds a border-bottom and expands the width of the clickable area of the logo
> fix: header styles and width

- src/index.scss
- src/js/components/ErrorInformation/404.jsx
- src/js/components/ErrorInformation/index.jsx
- src/js/components/UserInformation/Identicon.jsx
- src/js/pages/Arbitration/components/ReadChatLogs.jsx
- src/js/pages/Escrow/components/CancelEscrow.jsx
- src/js/pages/Escrow/components/CardEscrowSeller.jsx
- src/js/pages/Escrow/components/OpenDispute.jsx
- src/js/pages/Home/index.jsx
- src/js/pages/Home/index.scss
- src/js/utils/images.js
- src/js/wizards/Sell/2_Asset/components/SellerAssets.jsx
We'll just need to remember to up that when publishing to rinkeby or something
> Add version to home page

- src/css/bootstrap-overrides.scss
- src/js/components/Loading/__snapshots__/index.test.jsx.snap
- src/js/components/Loading/index.jsx
- src/js/components/Offer/index.jsx
- src/js/components/Reputation/__snapshots__/index.test.jsx.snap
- src/js/components/Reputation/index.jsx
- src/js/pages/OffersList/index.jsx
- add back ratting
- Was caused by a small conflict because the component is used both to display the rating and to do the rate action
- @richard-ramos let me know if you think I broke the rate action, but I think I made it work in both cases like this
- Fix the offer list as the there as a weird spacing and not the right colors
- Make the loader by default centered for when the css loads slow
> Add back rating an few small fixes

- src/js/features/escrow/actions.js
- src/js/features/escrow/saga.js
Add ENS resolution on contract code when creating an escrow, just like when creating an offer for Sellers
> fix(open-trade): fix ens resolution on create escrow

- src/js/components/Offer/index.jsx
- src/js/pages/OffersList/index.jsx
- src/js/utils/sorters.js
> feat(offer-list): group offers by user

- src/css/variable-overrides.scss
- src/index.scss
- src/js/features/license/saga.js
- src/js/pages/Escrow/index.jsx
- src/js/utils/numbers.js
- src/js/wizards/hoc/withFooter.scss
Also a small fix to get the License price
> Design for desktop

- src/js/features/metadata/saga.js
- src/js/pages/Escrow/components/CardEscrowBuyer.jsx
- src/js/pages/Escrow/components/OpenDispute.jsx
- src/js/pages/MyProfile/components/Offers.jsx
- src/js/pages/MyProfile/components/Trades.jsx
- src/js/services/embarkjs.js
- Fix profile links
- Fix opening a second trade or a second offer
- Fix canceled escrow page
- Fix google api error
> A couple fixes

- src/js/components/Reputation/__snapshots__/index.test.jsx.snap
- src/js/components/Reputation/index.jsx
- src/js/pages/Escrow/components/CardEscrowBuyer.jsx
- src/js/pages/MyProfile/components/__snapshots__/Offers.test.jsx.snap
- src/js/pages/MyProfile/components/__snapshots__/Trades.test.jsx.snap
- stories/components/reputation.stories.jsx
- stories/pages/buyerEscrow.stories.jsx
Fix the bug where when a buyer gave a rating to a seller, it would write "1 - 1" instead of only what the user gave.
Now, it shows in blue the rating the user gave.
Also added stories for the buyer escrow:
> Fix rating by buyer

- src/js/components/Offer/index.jsx
- src/js/components/UserInformation/Address.jsx
- src/js/components/UserInformation/Address.scss
- src/js/components/UserInformation/index.jsx
- src/js/pages/Arbitration/components/ContactUser.jsx
- src/js/pages/Arbitration/components/TradeParticipant.jsx
- src/js/pages/MyProfile/components/Disputes.jsx
- src/js/pages/MyProfile/components/Trades.jsx
- src/js/pages/MyProfile/components/__snapshots__/Trades.test.jsx.snap
- src/js/pages/MyProfile/index.jsx
- src/js/pages/Profile/index.jsx
- src/js/utils/address.js
- src/js/wizards/Buy/1_Trade/components/OfferTrade.jsx
- src/js/wizards/Buy/1_Trade/index.jsx
- stories/components/userInformation.stories.jsx
this will guarantee that once the "Open chat" buttons are pressed, the identicon presented for the user will match the one on the escrow
> feat: use contact code as seed for the identicons

- src/js/features/escrow/reducer.js
- src/js/locales/en.json
- src/js/pages/ArbitrationLicense/components/Info.jsx
- src/js/pages/ArbitrationLicense/index.jsx
This was just a small mistake of not using the right States property
Also, fixed a CRA warning in the ArbitrationPage
> Fix blank screen on cancel

- package.json
- src/js/components/EditContact/index.jsx
- src/js/pages/EditMyContact/index.jsx
- src/js/wizards/Buy/0_Contact/index.jsx
- src/js/wizards/Sell/0_Location/index.jsx
- src/js/wizards/Sell/1_Contact/index.jsx
- yarn.lock
React already has XSS protection, but this adds a small layer before we save to the chain, so that way, if the data is read somewhere else, it won't be in danger
> feat: add dompurify and sanitize text saved in the chain

- src/js/components/Map/index.jsx
- src/js/pages/OffersMap/index.jsx
This is for Status where it doesn't have the getCurrentPos feature
> fix(map): always show the default coords until we have the user pos

- src/js/components/Offer/index.jsx
- src/js/features/network/reducer.js
- src/js/features/network/selectors.js
- src/js/pages/OffersList/index.jsx
- src/js/wizards/Buy/1_Trade/components/OfferTrade.jsx
- src/js/wizards/Buy/1_Trade/index.jsx
Also change the color of the offer when it's your own offer
> Set max as sellers balance

- src/js/features/arbitration/selectors.js
> fix broken arbitration opening action

- src/js/features/arbitration/reducer.js
- src/js/features/metadata/actions.js
- src/js/features/metadata/reducer.js
- src/js/features/metadata/selectors.js
- src/js/utils/address.js
- src/js/wizards/Sell/4_SelectArbitrator/components/ArbitratorSelectorForm.jsx
- src/js/wizards/Sell/4_SelectArbitrator/index.jsx
Put much more info to the arbitrator select
Also, change the reducers so that we store only checksum addresses
> Improve arbitrator select

- src/js/pages/Escrow/components/EscrowDetail.jsx
> show expiration date when it is available

- src/js/features/escrow/reducer.js
- src/js/pages/Escrow/components/CardEscrowBuyer.jsx
- src/js/pages/Escrow/index.jsx
- src/js/pages/OffersList/index.jsx
- src/js/wizards/Buy/1_Trade/components/OfferTrade.jsx
- src/js/wizards/Buy/1_Trade/index.jsx
The old rate was a bit confusing as you clicked on it and it didn't show that it worked.
Now, you will see the result immediately
> Make it impossible to even try to rate twice

- embarkConfig/data.js
- src/js/features/metadata/reducer.js
- src/js/features/metadata/selectors.js
- src/js/features/newSeller/reducer.js
- src/js/wizards/Sell/6_Margin/index.jsx
Was mostly caused by the seller state not being reset after publishing an offer.
Maybe there is something more, but it worked for me
> Fix infinite loop in the Sell page and add txHash to addOffer

- src/js/pages/OffersList/index.jsx
Fixes payment method filter and asset filter. Also fix the number of seller (which used the number of offers instead of the sellers)
The location filter worked for me. Maybe I don,t remember if it worked on Status
> Fix filters

- src/index.scss
- src/js/components/UserInformation/index.jsx
- src/js/pages/Arbitration/components/ContactUser.jsx
- src/js/pages/Arbitration/components/EscrowDetail.jsx
- src/js/pages/Arbitration/components/TradeParticipant.jsx
- src/js/pages/Arbitration/index.jsx
- src/js/pages/Arbitration/index.scss
- src/js/pages/MyProfile/index.scss
> Add buyer or seller badge in arbitration

- src/index.scss
- src/js/features/arbitration/reducer.js
- src/js/features/arbitration/selectors.js
- src/js/features/escrow/helpers.js
- src/js/pages/Arbitration/components/ContactUser.jsx
- src/js/pages/Arbitration/components/TradeParticipant.jsx
- src/js/pages/Arbitration/index.jsx
- src/js/pages/Escrow/components/CardEscrowBuyer.jsx
- src/js/pages/Escrow/components/CardEscrowSeller.jsx
- src/js/pages/Escrow/components/ResolvedDispute.jsx
- src/js/pages/Escrow/index.jsx
- src/js/pages/MyProfile/components/Trades.jsx
- src/js/pages/MyProfile/components/__snapshots__/Trades.test.jsx.snap
- src/js/pages/OpenDispute/index.jsx
Arbitrator's page:
Loser's profile:
Winner's escrow:
> Show who won and lost arbitrations

- package.json
- src/js/wizards/Sell/6_Margin/components/MarginSelectorForm.jsx
- src/js/wizards/Sell/6_Margin/components/MarginSelectorForm.scss
- src/js/wizards/Sell/6_Margin/components/__snapshots__/MarginSelectorForm.test.jsx.snap
- yarn.lock
> feat(margin): use a slider for the margin selector

- shared.chains.json
- src/js/locales/en.json
- src/js/wizards/Buy/1_Trade/components/OfferTrade.jsx
> Improve trade page to make it clearer

- src/css/bootstrap-overrides.scss
- src/js/pages/MyProfile/components/Trades.jsx
- src/js/pages/MyProfile/components/__snapshots__/Trades.test.jsx.snap
- stories/pages/myProfile.stories.jsx
- stories/wizards/Sell/3_currency.stories.jsx
- stories/wizards/Sell/4_margin.stories.jsx
> fix: fix color of grey tags

- src/js/utils/numbers.js
Fixes the issue where you'd have 6 zeros at the end of the assets
> fix: remove useless zeros

- src/js/ui/BackButton/index.jsx
- src/js/wizards/Sell/6_Margin/components/MarginSelectorForm.jsx
- src/js/wizards/Sell/6_Margin/components/__snapshots__/MarginSelectorForm.test.jsx.snap
- src/js/wizards/Sell/6_Margin/index.jsx
- fix back button on home page
- fix 0 cost offers
- fix the margin input being too small on phones
> Fix small stuff

- src/js/pages/License/index.jsx
When use doesn't have enough balance, poll it every two seconds so it updates correctly
> feat: poll user balance when he doesn't have enough

- contracts/common/MessageSigned.sol
- contracts/teller-network/Escrow.sol
- contracts/teller-network/MetadataStore.sol
- test/escrow_spec.js
- test/funding_escrows_spec.js
- test/metadata_store_spec.js
Added signature to addOrUpdateUser as mentioned in #206
> Change MetadataStore#addOrUpdateUser

- contracts/teller-network/Escrow.sol
- contracts/teller-network/Fees.sol
- contracts/teller-network/MetadataStore.sol
- shared.chains.json
- src/js/utils/networks.js
- test/escrow_spec.js
Send 10% of the fee to the arbiter when no dispute, and 100% when there is a dispute.
> Send fees to the arbiter and /or the Staking pool

- contracts/teller-network/ArbitrationLicense.sol
- contracts/teller-network/MetadataStore.sol
- embarkConfig/data.js
- src/js/pages/MyProfile/components/Arbitrators.jsx
- src/js/pages/MyProfile/index.jsx
1. Added button to link to arbitrators
2. Updated metadata contract to avoid returning data from userId 0 if the user does not exist
3. Changed arbitration request process to state machine
> feat: miscellaneous stuff

- src/js/features/approval/actions.js
- src/js/features/approval/saga.js
- src/js/features/escrow/saga.js
- src/js/pages/Escrow/components/CardEscrowSeller.jsx
- src/js/pages/Escrow/index.jsx
SNT escrows went straight to funding instead of  approval.
Also, I'm pretty sure the approval was bugged, because we were approving only "ether" amounts and not wei amounts... so I'm not sure why it worked before. Just confirm that I'm doing the right thing and we'll be able to test later if the fees and everything is fine
> fix: approval of tokens

- shared.chains.json
- src/index.scss
- src/js/components/Offer/index.jsx
- src/js/pages/Profile/components/Offer.jsx
- src/js/pages/Profile/index.jsx
- Add a tooltip on disabled offers to explain why they are disabled
- Show for which offers you are the arbitrator and make the message clearer
I wasn't able to reproduce the bug we had @richard-ramos so it was either black magic or you failed when selecting the arbitrators haha
> Improve viewing offers for which you are the arbitrator

- src/js/pages/EditMyContact/index.jsx
Disable the update button is the code is not valid
> fix: disable updating if the contact code is not valid

- src/js/store.js
Was caused by a lint error 🤷‍♂
> Fix test build (CI)

- .soliumignore
- .soliumrc.json
- contracts/fees/KyberNetworkProxy.sol
- contracts/teller-network/ArbitrationLicense.sol
- contracts/teller-network/Escrow.sol
- contracts/teller-network/EscrowRelay.sol
- contracts/teller-network/IEscrow.sol
- contracts/token/MiniMeToken.sol
- package.json
- src/js/features/escrow/saga.js
- test/arbitration_spec.js
- test/escrow_relay_spec.js
- test/escrow_spec.js
- test/escrow_upgradability_spec.js
- test/funding_escrows_spec.js
- yarn.lock
I think embark-solium never actually worked. It was also using an older version
> Fix solc warnings and update embark-solium

- src/js/pages/OffersList/index.jsx
Makes it so searching for suburbs gives the big city
> increase location distance threshold

- embarkConfig/data.js
- src/js/components/Offer/index.jsx
- src/js/components/Offer/index.scss
- src/js/locales/en.json
- src/js/pages/Home/index.jsx
- src/js/pages/OffersList/components/SorterFilter.jsx
- src/js/pages/OffersList/components/SorterFilter.scss
- src/js/pages/OffersList/index.jsx
Changes the homepage and offer list, including the sorter-filter
Only thing that's left is the reputation to use numbers instead, will do that in another PR
> Re-design of the homepage and offer list

- embarkConfig/data.js
- src/js/components/Offer/index.jsx
- src/js/components/Offer/index.scss
- src/js/components/Reputation/__snapshots__/index.test.jsx.snap
- src/js/components/Reputation/index.jsx
- src/js/components/Reputation/index.scss
- src/js/features/escrow/saga.js
- src/js/features/metadata/reducer.js
- src/js/pages/MyOffers/components/Offers.jsx
- src/js/pages/MyOffers/components/__snapshots__/Offers.test.jsx.snap
- src/js/pages/MyProfile/components/__snapshots__/StatusContactCode.test.jsx.snap
- src/js/pages/MyTrades/components/__snapshots__/Trades.test.jsx.snap
- src/js/pages/OffersList/index.jsx
Changes the reputation on the offer list to be a color coded numeric value. 
This does not affect other pages as the design wasn't ready and maybe we don,t want to change them?
> Change reputation on the offer list

- src/css/bootstrap-overrides.scss
- src/js/components/Reputation/index.jsx
- src/js/components/Reputation/index.scss
- src/js/pages/Escrow/components/Done.jsx
- src/js/pages/Escrow/components/FundingEscrow.jsx
- src/js/pages/Escrow/components/ReleaseFunds.jsx
- src/js/pages/Escrow/components/SendMoney.jsx
- src/js/pages/Escrow/index.jsx
> Add back rating and add triangles to bubbles

- src/css/bootstrap-overrides.scss
- src/js/components/Reputation/index.jsx
- src/js/components/Reputation/index.scss
- src/js/layout/App.jsx
- src/js/pages/Escrow/components/Done.jsx
- src/js/pages/Escrow/components/FundingEscrow.jsx
- src/js/pages/Escrow/components/ReleaseFunds.jsx
- src/js/pages/Escrow/components/SendMoney.jsx
- src/js/pages/Escrow/index.jsx
- src/js/pages/Escrow/index.scss
> Add see all actions button to escrow page

- src/js/ui/CheckButton/index.jsx
- src/js/ui/CheckButton/index.scss
- src/js/wizards/Buy/1_Trade/index.jsx
- src/js/wizards/Sell/3_PaymentMethods/components/SellerPaymentMethod.jsx
- src/js/wizards/Sell/6_Margin/components/__snapshots__/MarginSelectorForm.test.jsx.snap
- src/js/wizards/Sell/7_Limits/components/LimitForm.jsx
> Make payment methods checkboxes

- src/js/layout/App.jsx
- src/js/wizards/Buy/0_Trade/index.jsx
- src/js/wizards/Buy/1_Contact/index.jsx
- src/js/wizards/Buy/2_ConfirmTrade/index.jsx
Also helps not having to sign then straight after sign the tx
I know that it's ugly. It's a placeholder while waiting for the design
> feat: add confirm trade page to confirm trade infos

- src/js/components/Reputation/__snapshots__/index.test.jsx.snap
- src/js/pages/Escrow/components/ReleaseFunds.jsx
- src/js/pages/Escrow/components/SendMoney.jsx
- src/js/pages/Escrow/index.jsx
- src/js/pages/MyTrades/components/__snapshots__/Trades.test.jsx.snap
> Add I got the payment as a seller

- src/js/pages/OffersList/components/SorterFilter.jsx
- src/js/pages/OffersList/components/SorterFilter.scss
Still missing the "Best price" filter. I'm still not sure how to implement this
> fix: filter v1 UI bugs

- src/js/layout/Header/index.jsx
- src/js/pages/Escrow/index.jsx
- src/js/pages/OffersList/index.jsx
1. Check if the fiat currency is correct. i.e.: I selected VEF for an offer, yet in the offer list it displays ARS
2. If you create a ETH offer, you dont need to approve the token.
3. Fix in "manage sellers" the profile button to display an "X"
> fix: various

- src/js/pages/OffersList/components/SorterFilter.jsx
- src/js/pages/OffersList/components/SorterFilter.scss
The scroll bar was appearing on top of the button and was sticking to the text
> fix(sorter-filter): fix filter style

- package.json
- src/index.js
- src/js/components/Offer/index.jsx
- src/js/components/Offer/index.scss
- src/js/features/metadata/reducer.js
- src/js/features/metadata/saga.js
- src/js/pages/OffersList/index.jsx
- src/js/services/googleMap.js
- yarn.lock
> feat: add country flags

- src/js/features/metadata/saga.js
- src/js/features/network/reducer.js
- src/js/pages/Arbitrators/index.jsx
- src/js/pages/Home/index.jsx
- src/js/pages/MyOffers/index.jsx
- src/js/wizards/Buy/0_Trade/components/OfferTrade.jsx
The scroll problem was just the Row having paddings when it shouldn't
The enable ethereum is when you connect directly to the node (for us in dev)
> Fix weird scroll in the buyer wizard and enable ethereum in direct connection

- src/js/locales/en.json
- src/js/pages/Escrow/components/CancelEscrow.jsx
> feat: clarify expiration by adding the time until

- contracts/fees/KyberFeeBurner.sol
- embarkConfig/contracts.js
- Adds a max slippage rate value
- Allows users to swap specific amounts
> feat: slippage rate protection

- src/js/components/PriceWarning/index.js
- src/js/pages/Escrow/components/Done.jsx
- src/js/pages/Escrow/index.scss
- src/js/ui/RatingIcon/index.jsx
> feat: add thumb at the end  of escrow and rating

- src/css/bootstrap-overrides.scss
- src/js/features/metadata/reducer.js
- src/js/ui/CheckButton/index.jsx
- src/js/ui/CheckButton/index.scss
- src/js/wizards/Sell/0_Asset/components/SellerAssets.jsx
- src/js/wizards/Sell/0_Asset/components/SellerAssets.scss
> feat: add asset name to asset list

- src/css/variable-overrides.scss
- src/js/components/EditContact/__snapshots__/index.test.jsx.snap
- src/js/pages/SellerApproval/SellerApprovalItem.jsx
- src/js/pages/SellerApproval/index.jsx
- stories/pages/myProfile.stories.jsx
> feat: new design for the arbitrator approval page

- embarkConfig/data.js
- src/js/layout/App.jsx
- src/js/pages/Escrow/components/OpenChat.jsx
- src/js/pages/ProfileSettings/index.jsx
- src/js/pages/Settings/index.js
I was tired of not having a button to go to the reset cache page 🤷‍♂
> Add cache settings button

- src/js/components/Offer/index.jsx
- src/js/pages/License/components/Info.jsx
- src/js/pages/OffersList/components/SorterFilter.jsx
- src/js/pages/OffersList/index.jsx
> feat: add comm method filter and check box to see comm method

- src/js/features/metadata/reducer.js
- src/js/features/metadata/saga.js
- src/js/pages/Home/components/landingFooter.jsx
- src/js/pages/MyTrades/components/Trades.jsx
This was caused because we only got the nb from the last offer
> Fix the nb of trades sometimes reseting

- src/js/features/metadata/selectors.js
- src/js/utils/images.js
- src/js/utils/transaction.js
Will show an unknown token instead, you can clear the cache to fix
> fix: no longer crash on old cache

- src/js/pages/Escrow/components/Done.jsx
This was probably caused by bad rebases
> fix: fix weird rating ui

- src/js/components/PriceWarning/index.js
- src/js/features/metadata/reducer.js
- src/js/pages/Escrow/components/EscrowDetail.jsx
- src/js/pages/Escrow/index.jsx
- src/js/pages/Escrow/index.scss
- src/js/utils/strings.js
- src/js/wizards/Buy/0_Trade/components/OfferTrade.jsx
The contact data was wrong because we reversed them by accident.
I also removed the See all option and added a util function to render the contact method + a message if the user has no contact method
> Fix wrong contact data shown + small fixes

- src/js/pages/EditLocation/index.jsx
- src/js/pages/MyOffers/components/Offers.jsx
- src/js/wizards/Sell/4_1_ContactName/index.jsx
- src/js/wizards/Sell/6_Margin/components/MarginSelectorForm.jsx
> Fix limits for margin selector

- src/js/components/Offer/index.jsx
- src/js/locales/en.json
- src/js/pages/Home/index.jsx
- src/js/pages/OffersList/index.jsx
also put in bold the method when filtering
> feat: limit number of payment methods to show

- contracts/teller-network/Escrow.sol
- contracts/teller-network/EscrowRelay.sol
- contracts/teller-network/IEscrow.sol
- embarkConfig/data.js
- src/js/features/escrow/saga.js
- test/arbitration_spec.js
- test/escrow_relay_spec.js
- test/escrow_spec.js
- test/escrow_upgradability_spec.js
- test/funding_escrows_spec.js
- test/offer_stake_spec.js
UI will keep the same behavior as before
> feat: Allow specifying different destination for escrow funds

- src/js/components/ErrorInformation/index.jsx
- src/js/features/network/reducer.js
- src/js/features/network/saga.js
- src/js/features/network/selectors.js
- src/js/layout/App.jsx
- src/js/locales/en.json
A little hacky and probably should be replaced with something that uses the environment from embark
> fix: display wrong network error

- src/js/features/escrow/selectors.js
Could possibly because of an old cache too
Now it will appear as a ??? token, showing you have to reload the cache
> fix: token not set yet when loading

- src/js/wizards/hoc/withFooter.scss
> fix: remove white bg on Next btn

- package.json
- public/index.html
- src/js/services/googleMap.js
- yarn.lock
We were using the sever side Google Geocoding API by accident, so we ended up getting blocked on the client side. Now, we use the client side API, so it works
> fix: use geocoding client side API instead of server side one

- embarkConfig/data.js
- src/js/components/Offer/index.jsx
- src/js/locales/en.json
- src/js/pages/OffersList/index.jsx
- src/js/ui/RoundedIcon/index.scss
- src/js/wizards/Buy/0_Trade/components/OfferTrade.jsx
- src/js/wizards/Buy/0_Trade/index.jsx
> fix: better display is you are owner and arbitrator on offer

- src/js/features/prices/saga.js
Fixes the problem when we reach the API limit
> fix: fix prices saga to fallback as soon as we have an error

- src/js/components/ErrorInformation/index.jsx
- src/js/layout/App.jsx
> fix: show page when an error is caught in one of the components

- package.json
- public/index.html
- src/js/pages/OffersList/index.jsx
- src/js/services/googleMap.js
- yarn.lock
So, we were using the CDN <script>, but it caused issues of loading in time and it's also ugly and bad.
I changed it to a client library with a real load and strict error management, so if anything goes wrong, we catch the error.
Also, fix the calculation of the distance, by using the right param
> fix: fix google map to use a lib instead of the CDN

- src/css/bootstrap-overrides.scss
- src/js/components/EditContact/ContactList.jsx
- src/js/components/Offer/index.jsx
- src/js/components/PriceWarning/index.jsx
- src/js/locales/en.json
- src/js/pages/EditMyContact/components/UpdateButton.jsx
- src/js/wizards/Buy/0_Trade/components/OfferTrade.jsx
- test/escrow_spec.js
See the commit messages to see what was fixed
> A couple of UI fixes

- src/js/pages/OffersList/components/Modals/CurrencyModal.jsx
- src/js/pages/OffersList/components/SorterFilter.jsx
- src/js/pages/OffersList/components/SorterFilter.scss
Most important fix is for the currency modal. It was not possible to press backspace without it exiting the modal.
> Couple of fixes to the filters

- src/js/layout/App.jsx
- src/js/wizards/Buy/2_ConfirmTrade/index.jsx
Also remove contact detail page if already set in buy wizard
> fix: change Back in Open Trade failure to go back to summary

- src/js/features/metadata/saga.js
- src/js/layout/App.jsx
This reduces the pollution of the hundreds of action calls
> refactor: change check account to do the interval in the saga

- src/js/pages/Home/components/landingFooter.jsx
add Subspace, Vac and Assemble to the footer as below
The order of the Status Network projects is
- Products
- Dev Tools
- Infra
(Suggested by Jonny)
> update the footer

- .travis.yml
This is so CI can actually start running
> update yarn version so that CI doesn't fail

- src/js/features/metadata/selectors.js
- src/js/features/network/selectors.js
- src/js/pages/Home/index.jsx
- src/js/pages/OffersList/components/Modals/ContactMethodModal.jsx
- src/js/pages/OffersList/components/Modals/CurrencyModal.jsx
- src/js/pages/OffersList/components/Modals/PaymentMethodModal.jsx
- src/js/pages/OffersList/components/SorterFilter.jsx
- src/js/pages/OffersList/index.jsx
- src/js/utils/sorters.js
Also only show payment methods that are actually used in offers
> Order filters by number of offers

- shared.rinkeby.json
- src/js/components/EditContact/ContactList.jsx
- src/js/features/newBuy/reducer.js
- src/js/features/newSeller/reducer.js
- src/js/wizards/Buy/1_2_ContactDetails/index.jsx
- src/js/wizards/Sell/4_2_ContactDetails/index.jsx
Going back in the wizard after entering the contact code would make a lot of stuff not work. Example: Autofil
> fix: fix contact forms in wizards not working anymore after backing

- src/js/features/metadata/saga.js
- src/js/locales/en.json
- src/js/wizards/Buy/0_Trade/components/OfferTrade.jsx
> Fix limitless offers to just show a warning when higher than the balance

- src/js/components/Offer/index.jsx
- src/js/ui/LoadingRectangle/index.jsx
- src/js/ui/LoadingRectangle/index.scss
> fix: add loading rectangle for price missing

- package.json
- src/index.scss
- src/js/locales/en.json
- src/js/pages/Escrow/components/DisputeWarning.jsx
- src/js/pages/Escrow/components/EscrowDetail.jsx
- src/js/pages/Escrow/components/Profile.jsx
- src/js/pages/Escrow/index.jsx
- src/js/pages/MyProfile/components/ProfileButton.jsx
- src/js/pages/MyTrades/components/Trades.jsx
- src/js/ui/RoundedIcon/index.jsx
- yarn.lock
Adds information on how the fallback arbitration work and info when the arbitration expires
Also, I updated react-script to 3.4 to support the new experimental babel feature (eg: ? and ??)
> Add UI for users when the arbitration expires

- src/js/locales/en.json
- src/js/pages/Escrow/components/CancelDispute.jsx
- src/js/pages/Escrow/components/CancelEscrow.jsx
- src/js/pages/Escrow/components/EscrowDetail.jsx
- src/js/pages/Escrow/components/OpenDispute.jsx
- src/js/pages/Escrow/index.jsx
- src/js/pages/MyDisputes/components/Disputes.jsx
- src/js/pages/MyDisputes/index.jsx
Follow up on the other PR. This one merges in the other
> UI for fallback arbi

- src/js/components/EditLocation/SellerPosition.jsx
- src/js/layout/App.jsx
- src/js/locales/en.json
- src/js/wizards/Sell/3_Location/index.jsx
- src/js/wizards/hoc/withFooter.jsx
> feat: show location form always and show a modal if you change it
